#!/usr/bin/env python3
from sys import argv
from performance import performance
from types import *
from core import *
from parser import *
from program import compilerHost


def executeCommandLine(args):
	commandLine = parseCommandLine(args)